# Generated by Django 4.2.9 on 2025-12-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "worker", "verbose_name_plural": "workers"},
        ),
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.IntegerField(default=12000),
            preserve_default=False,
        ),
    ]
