# Generated by Django 4.1 on 2026-02-06 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_project_description_alter_tag_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='workers',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
