# Generated by Django 4.1 on 2026-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_project_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('IN_PROCESS', 'in process'), ('DONE', 'done'), ('PAUSED', 'paused'), ('CANCELED', 'canceled')], default='IN_PROCESS', max_length=255),
        ),
    ]
