# Generated by Django 4.1 on 2026-02-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_remove_project_is_active_project_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stage',
            new_name='status',
        ),
    ]
